### ISSUE TITLE
Missing refreshMemory()

### ISSUE THREAD

**Issue by davedoesdev** [devsnek/node-wasi#10]
I was getting this error:

```
(node:17324) UnhandledPromiseRejectionWarning: TypeError: Cannot perform DataView.prototype.setUint8 on a neutered ArrayBuffer
    at DataView.setUint8 (<anonymous>)
    at /home/david/mce.new/js/node_modules/wasi/index.js:649:19
    at /home/david/mce.new/js/node_modules/wasi/index.js:427:12
    at __isatty (wasm-function[10486]:33)
    at __stdout_write (wasm-function[10487]:32)
    at __fwritex (wasm-function[10510]:171)
    at fwrite (wasm-function[10511]:16)
    at std::__2::__stdoutbuf<char>::overflow(int) (wasm-function[9355]:182)
    at std::__2::basic_streambuf<char, std::__2::char_traits<char> >::sputc(char) (wasm-function[9057]:155)
    at std::__2::ostreambuf_iterator<char, std::__2::char_traits<char> >::operator=(char) (wasm-function[9270]:131)
```

Seem to be fixed with:

```diff
diff --git a/index.js b/index.js
index e9f2e2d..dcb25bd 100644
--- a/index.js
+++ b/index.js
@@ -644,6 +644,7 @@ class WASI {
       },
       fd_fdstat_get: wrap((fd, bufPtr) => {
         const stats = CHECK_FD(fd, 0);
+        this.refreshMemory();
         this.view.setUint8(bufPtr, stats.filetype); // FILETYPE u8
         this.view.setUint16(bufPtr + 2, 0, true); // FDFLAG u16
         this.view.setUint16(bufPtr + 4, 0, true); // FDFLAG u16
```

**Comment by devsnek** [comment]
would you mind PRing that patch?
